updated workflow

diff --git a/.github/workflows/build-analyze-test.yml b/.github/workflows/build-analyze-test.yml
--- a/.github/workflows/build-analyze-test.yml
+++ b/.github/workflows/build-analyze-test.yml
@@ -33,7 +33,7 @@ jobs:
       - name: Checkout
         uses: actions/checkout@v3
 
-      - name: Set Destinations
+      - name: Check Destinations
         run: |
           result=$(./.github/workflows/id_devices.sh)
           if test ${#result} -eq 0; then
@@ -41,7 +41,6 @@ jobs:
             exit 1
           fi
           echo Destination String: $result
-          echo "result=$result" >> $GITHUB_ENV
       
       - name: Set Default Scheme
         run: |
@@ -108,6 +107,16 @@ jobs:
     needs: [build]
 
     steps:
+
+      - name: Set Destinations
+        run: |
+          result=$(./.github/workflows/id_devices.sh)
+          if test ${#result} -eq 0; then
+            echo "::error::No device destinations"
+            exit 1
+          fi
+          echo Destination String: $result
+          echo "result=$result" >> $GITHUB_ENV
 
       - name: Test
         run: |
