updated test workflow

diff --git a/.github/workflows/xcode-test-workflow.yml b/.github/workflows/xcode-test-workflow.yml
--- a/.github/workflows/xcode-test-workflow.yml
+++ b/.github/workflows/xcode-test-workflow.yml
@@ -27,7 +27,10 @@ jobs:
     steps:
 
       - name: Clear Work Directory
-        run: rm -rf *
+        run: |
+         rm -rf *
+         pwd
+         ls
 
       - name: Checkout
         uses: actions/checkout@v3
@@ -76,18 +79,32 @@ jobs:
           -allowProvisioningDeviceRegistration \
           -resultBundlePath TestResults | xcpretty && exit ${PIPESTATUS[0]}
 
-      - name: Generate Results
+      # - name: Generate Results
+      #   uses: kishikawakatsumi/xcresulttool@main
+      #   with:
+      #     path: TestResults.xcresult
+      #     show-code-coverage: false
+      #   if: success() || failure()
+
+      # - name: Generate Code Coverage
+      #   uses: kishikawakatsumi/xcresulttool@main
+      #   with:
+      #     path: TestResults.xcresult
+      #     show-passed-tests: false
+      #     title: Code Coverage
+      #   if: success() || failure()
+  
+  generate:
+    name: Generate Test Results
+    runs-on: test-runner
+
+    steps:
+      - name: Download Artifact
+        uses: actions/download-artifact@v3.0.0
+      
+      - name: Run Action
         uses: kishikawakatsumi/xcresulttool@main
         with:
           path: TestResults.xcresult
           show-code-coverage: false
         if: success() || failure()
-
-      - name: Generate Code Coverage
-        uses: kishikawakatsumi/xcresulttool@main
-        with:
-          path: TestResults.xcresult
-          show-passed-tests: false
-          title: Code Coverage
-        if: success() || failure()
-
